---
# tasks file for apache
- name: install httpd
  ansible.builtin.yum:
     name: httpd
     state: present

- name: copy index.html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html

- name: start httpd
  ansible.builtin.service:
    name: httpd
    state: started
